Proyecto1/Dashboard/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Dashboard.views import DashboardClass


app_name = 'Dashboard'
urlpatterns = [
    path('',DashboardClass.as_view(), name = 'dashboard'),
]

Proyecto1/Landing/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_view
from Landing.views import LandingClass



app_name = 'Landing'
urlpatterns = [
    path('',LandingClass.as_view(), name = 'Landing'),
]

Proyecto1/Login/urls.py
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views
from django.contrib.auth import views as auth_views
from Login.views import LoginClass

#VISTAS
# from Login.views import Index
# from Login.views import Landing
#URL QUE MANEJAN LOS PARAMETROS DASHBOARD
app_name = 'Login'
urlpatterns = [
    path('',LoginClass.as_view(), name='login'),
]

Proyecto1/Proyecto1/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('Landing.urls')),
    path('login/', include('Login.urls')),
    path('dashboard/',include('Dashboard.urls')),
    path('registro/',include('Registro.urls')),
    path('logout/',logout_then_login, name='logout'),
 
]

Proyecto1/Registro/urls.py
from django.urls import include, re_path,path 
from django.conf import settings
from django.contrib.auth import views as auth_view
from Registro.views import RegistrateView


app_name = 'Registro'
urlpatterns = [
    path('',RegistrateView.as_view(), name = 'registro'),
]

Proyecto1/Almacen/models.py
from django.db import models

# Create your models here.
class ModelProducts(models.Model):
     nombreProduct=models.CharField(max_length=254, null=False);
     fechaProduct = models.CharField(max_length=254, null=False);
     fechaCaducidad= models.CharField(max_length=254, null=False);
     cantidad = models.IntegerField(null=False);
     venta= models.CharField(max_length=254, null=False);
     

Proyecto1/Alumno/models.py
from django.db import models

# Create your models here.
class Materia(models.Model):
    nombreMateria = models.CharField(max_length=254, null=False)

class Alumno(models.Model):
    Materia = models.ForeignKey(Materia,on_delete = models.CASCADE)
    name = models.CharField(max_length=254, null=False)
    carrera = models.CharField(max_length=254, null=False)
    edad = models.IntegerField(null=False)
    direccion =  models.CharField(max_length=254, null=False)
    genero =  models.CharField(max_length=254, null=False)
    matricula =  models.CharField(max_length=254, null=False)

Proyecto1/Login/models.py
from django.db import models

# Create your models here.

Proyecto1/Registro/models.py
from django.db import models

# Create your models here.

Proyecto1/Registro/forms.py
from django.contrib.auth.models import User
from django import forms

ERROR_MESSAGE_USER = {'unique' : 'El Username ya se encuentra registrado', 'invalid' : 'usuario o contraseña incorrecto'}
ERROR_MESSAGE_PASSWORD = {'required' : 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'invalid' : 'Ingrese un correo valido'}
ERROR_MESSAGE_PHONE = {'invalid' : 'Formato numero incorrecto'}


class RegisterBusinessForm(forms.ModelForm):
    first_name = forms.CharField(label='', required=True)
    last_name = forms.CharField(label='', required=True)
    password = forms.CharField(max_length = 20,required=True, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD )
    email = forms.CharField( required = True, error_messages = ERROR_MESSAGE_EMAIL)

    def __init__(self, *args, **kwargs):
        super(RegisterBusinessForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update( {'id': 'username_create', 'class': 'form-control', 'placeholder': 'usuario'} ) # Esto es un input en HTML <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name = "password" required>
        self.fields['first_name'].widget.attrs.update( {'id': 'first_name_create', 'class': 'form-control', 'placeholder': 'Nombre'} )
        self.fields['last_name'].widget.attrs.update( {'id': 'last_name_create', 'class': 'form-control', 'placeholder': 'Apellidos'} )
        self.fields['password'].widget.attrs.update( {'id': 'password_create', 'class': 'form-control', 'placeholder': 'Contraseña'} )
        self.fields['email'].widget.attrs.update( {'id': 'email_create', 'class': 'form-control', 'placeholder': 'Correo Electrónico'} )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

Proyecto1/Almacen/views.py
from django.shortcuts import render

# Create your views here.

Proyecto1/Alumno/views.py
from django.shortcuts import render

# Create your views here.

Proyecto1/Dashboard/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

class DashboardClass(LoginRequiredMixin, View):
    template_ok= 'dashboard.html'
    def get(self,request, * args, ** kwargs):
        return render(request,self.template_ok,{})

Proyecto1/Landing/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import redirect
from django.contrib.auth import authenticate

class LandingClass(View):
    templates_ok = 'Landing.html'
    def get(self, request, *args, **kwargs):
        return render(request,self.templates_ok,{})

Proyecto1/Login/views.py
from django.shortcuts import render 
from django.views.generic import View
from django.contrib.auth import authenticate
from django.shortcuts import redirect
from django.contrib.auth import login as login_django
 

class LoginClass(View):

    templates='index.html'

    def get(self,request, *args,**kwargs,):
        if request.user.is_authenticated:
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:dashboard')
        return render(request, self.templates,{})

    def post(self,request, *args,**kwargs,):
        userPost=request.POST['user']
        passwordPost=request.POST['password']
        user_session = authenticate(username = userPost, password = passwordPost)
        #ACÁ LO VALIDO
        if user_session is not None:
            login_django(
                request, user_session
            )
            next_url = request.GET.get('next')
            print(user_session.username)
            if next_url:
                return redirect(next_url)
            else:
                return redirect('Dashboard:dashboard')
        else:
            self.message = 'Usuario o contraseña incorrecto'

        return render(request, self.templates,self.getContext())
    def getContext(self):
        return{
            'error':self.message,
        }

Proyecto1/Registro/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from Registro.forms import RegisterBusinessForm


# Create your views here.

class RegistrateView(FormView):
    template_name = 'registro.html'

    # GET
    def get(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.GET or None)
        context = {
        'form_get' : form
        }
        return render(request, self.template_name, context)

    # POST
    def post(self, request, *args, **kwargs):
        form = RegisterBusinessForm(request.POST or None)
        if form.is_valid():
            self.object = form.save(commit = False)
            self.object.set_password(self.object.password)
            self.object.save()
        return redirect('Login:login')

Proyecto1/Dashboard/templates/dashboard.html
{% load static %}
<! DOCTYPE html />
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="{% static 'desing/style.css' %}" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div class ="dash">
            <h1 style = "text-align:center">BIENVENIDO</h1>
            <h1>Usuario: {{ user.username | upper}} </h1>
            <br>
            <h1>Email: {{ user.email }}</h1>
            <br>
            <br>
            <a  href= "{% url 'logout' %}">Cerrar sesion</a>
        </div>

    </body>
</html>

Proyecto1/Landing/templates/Landing.html
{% load static %}
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">
    <link href="{% static 'desing/style.css' %}" type="text/css" rel="stylesheet">

    <title>Como integrar Django y Bootstrap 4 </title>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}
    


</head>

<body >
    
    <br>
    <div class="form-group" style="text-align: center">
        <img class="rounded-circle border border-white" style="width: 200px" 
            src="https://as2.ftcdn.net/jpg/02/29/75/83/500_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg" >
    </div>
    <br>
    <div class="mx-auto" style="width:50%">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://www.tortugaswiki.com/Imagenes/guia-basica-de-las-tortugas.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://elsouvenir.com/wp-content/uploads/2016/07/ruta-de-la-tortuga.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Second slide label</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://i.pinimg.com/originals/d6/9f/2f/d69f2f3248bb2cf223f52e28e57859be.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Third slide label</h5>
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <br>
    <br>
    <div style = "text-align:center;">
        <a href = "{% url 'Login:login'%}">Ir al login</a>
      </div>

    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

<footer>

</footer>

</html>

Proyecto1/Login/templates/index.html
{% load static %}
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'desing/style.css' %}" type="text/css" rel="stylesheet">


    {% load bootstrap4 %}

    {% bootstrap_css %}


</head>

<body >
    <br>
    <br>
    <div class="logo">
        <br>
        <div class="container">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group" style="text-align: center">
                    <img src="https://as2.ftcdn.net/jpg/02/29/75/83/500_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.jpg" style="width: 150px" class="rounded-pill">
                    <br>
                    <br>
                    <input type="text" class="form-control " placeholder="Usuario" name="user" required>
                    <br>
                    <br>
                    <br>
                    <input type="password" class="form-control" placeholder="Contraseña" name="password" required>
                    <br>
                    <br>
                    </div>
                    <div style="text-align: center">
                    <button type="submit" class="btn btn-secondary">Iniciar</button>
                    <br>
                    <br>
                    {% if error%}
                    <div class="alert alert-warning" role="alert">
                        {{error}}
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>
        <div style = "text-align:center;">
            <a href = "{% url 'Landing:Landing'%}">Ir a landing</a>
            <br>
            <a href = "{% url 'Registro:registro'%}">Registro</a>
          </div>
    </div>
    
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

</html>

Proyecto1/Registro/templates/registro.html
{% load static %}
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'desing/style.css' %}" type="text/css" rel="stylesheet">

    {% load bootstrap4 %}

    {% bootstrap_css %}

</head>

<body>
    <div class="registro">
        <br>
        <div class="container">
            <form method="POST">
                <h1 style = "text-align:center;">Registro</h1>
                <br>
                
                {% csrf_token %}
                    {% if form_get.username.value %}
                    {{ form_get.username }}
                    {% else %}
                    {{ form_get.username }}
                    {% endif %}
                    <br>
                    {% if form_get.first_name.value %}
                    {{ form_get.first_name }}
                    {% else %}
                    {{ form_get.first_name }}
                    {% endif %}
                    <br>
                    {% if form_get.last_name.value %}
                    {{ form_get.last_name }}
                    {% else %}
                    {{ form_get.last_name }}
                    {% endif %}
                    <br>
                    {% if form_get.password.value %}
                    {{ form_get.password }}
                    {% else %}
                    {{ form_get.password }}
                    {% endif %}
                    <br>
                    {% if form_get.email.value %}
                    {{ form_get.email }}
                    {% else %}
                    {{ form_get.email }}
                    {% endif %}
                    <br>
                    <br>
                    <div style = "text-align:center;" >
                        <button type="submit" class="btn btn-secondary">Registrate </button>
                        <br>
                        <br>    
                    </div>
                    <div style = "text-align:center;">
                        <a href = "{% url 'Landing:Landing'%}">Ir a landing</a>
                       
                      </div>  
            </form>
        </div>
    </div>
    
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

Proyecto1/templates/Dashboard/dashboard.html
<h1> Soy Dashboard</h1>

Proyecto1/templates/Landing/Landing.html
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Como integrar Django y Bootstrap 4 </title>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %}


</head>

<body>
    <br>
    <div class="form-group" style="text-align: center">
        <img class="rounded-circle border border-white" style="width: 200px" 
            src="https://comosellama.net/wp-content/uploads/2015/02/Como-se-llama-la-tortuga-de-Buscando-a-Nemo.jpg" >
    </div>
    <br>
    <div class="mx-auto" style="width:50%">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://4.bp.blogspot.com/-xrYv6jL52w8/UJXTG5CF6LI/AAAAAAAAA2A/sDYfjuAR7GU/s640/pescaditos%2Benamorados.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://okdiario.com/img/2017/09/03/todo-lo-que-debes-saber-sobre-los-peces-5-655x368.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Second slide label</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="https://3.bp.blogspot.com/-IT1O6OWo1-I/Thwr7w6DaAI/AAAAAAAAAQU/j8Vh4A4p6pU/s1600/Pez+Asustado.jpg"
                        class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Third slide label</h5>
                        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <br>
    <br>
    <div style = "text-align:center;">
        <a href = "{% url 'Login:login'%}">Ir al login</a>
      </div>

    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

<footer>

</footer>

</html>

Proyecto1/templates/login/index.html
<! doctype html />
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    {% load bootstrap4 %}

    {% bootstrap_css %}


</head>

<body>
    <br>
    <br>
    <div class="mx-auto border  border-dark" style="width:200px">
        <br>
        <div class="container">
            <form action=" " method="POST">
                {% csrf_token %}
                <div class="form-group" style="text-align: center">
                    <img src="https://sic.cultura.gob.mx/images/63227" style="width: 100px" class="rounded-pill">
                    <br>
                    <br>
                    <input type="text" class="form-control " placeholder="Correo" name="user" required>
                    <br>
                    <br>
                    <input type="password" class="form-control" placeholder="Contraseña" name="password" required>
                    <br>
                    </div>
                <div style="text-align: center">
                    <button type="submit" class="btn btn-secondary">Iniciar</button>
                    <br>
                    {% if error%}
                    <div class="alert alert-warning" role="alert">
                        {{error}}
                    </div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <br>
    <br>
    <div style = "text-align:center;">
        <a href = "{% url 'Login:Landing'%}">Ir a landing</a>
      </div>
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

</html>